#!/bin/sh

LOCAL_FILE=$1
REMOTE_FILE=$2
HOSTNAME=`hostname`

if [ "$LOCAL_FILE" = "" ]; then
  echo "ColdFire Copy Program (cfcp) usage:"
  echo "cfcp <localfile> <remotefile>"
  exit 1;
fi

if [ ! -x $LOCAL_FILE ]; then
  echo "Unable to read file $LOCAL_FILE."
  exit 1;
fi


ftp -n -i cf-server.uwaterloo.ca << @__EOF__
user cf_user 354cfU2
bin
put $LOCAL_FILE $REMOTE_FILE
bye
@__EOF__

echo
echo "Sent $LOCAL_FILE to cf-server as $REMOTE_FILE"
echo

exit 0;


